CREATE TABLE `fc_timer_tasks` (
	`ID` VARCHAR(50) NOT NULL,
	`IMAGE_TOKEN` VARCHAR(50) NOT NULL,
	`SOURCE_FILE_TYPE` VARCHAR(10) NOT NULL,
	`SOURCE_FILE_MD5` VARCHAR(50) NOT NULL,
	`SOURCE_FILE_PATH` VARCHAR(500) NOT NULL,
	`TARGET_FILE_TYPE` VARCHAR(10) NOT NULL,
	`TARGET_FILE_MD5` VARCHAR(50) NULL DEFAULT NULL,
	`TARGET_FILE_PATH` VARCHAR(500) NULL DEFAULT NULL,
	`HANDLE_CODE` VARCHAR(50) NULL DEFAULT NULL,
	`HANDLE_TIME` DATETIME NULL DEFAULT NULL,
	`HANDLE_STATE` VARCHAR(50) NULL DEFAULT NULL,
	`HANDLE_MSG` VARCHAR(500) NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NULL DEFAULT NULL,
	`LAST_UPDATE_TIME` DATETIME NULL DEFAULT NULL,
	`HANDLE_COUNT` INT(11) NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
)
COMMENT='文件转换定时任务'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;